./ ADD NAME=BCC      0100-04042-04042-1043-00069-00069-00000-PDPCLIB
CC=bcc
COPTS=-w -c -I. -u- -O2

pdptest.exe: startup.obj pdptest.obj stdio.obj string.obj stdlib.obj \
       start.obj time.obj errno.obj assert.obj signal.obj locale.obj \
       ctype.obj setjmp.obj math.obj fpfuncsb.obj
  if exist borland.lib del borland.lib
  tlib borland +startup.obj
  tlib borland +stdio.obj
  tlib borland +string.obj
  tlib borland +stdlib.obj
  tlib borland +start.obj
  tlib borland +time.obj
  tlib borland +errno.obj
  tlib borland +assert.obj
  tlib borland +signal.obj
  tlib borland +locale.obj
  tlib borland +ctype.obj
  tlib borland +setjmp.obj
  tlib borland +math.obj
  tlib borland +fpfuncsb.obj
  tlink pdptest,pdptest.exe,nul.map,borland.lib+e:\bcos2\lib\os2.lib

startup.obj: startup.asm
  tasm -mx -w2 startup.asm

start.obj: start.c
  $(CC) $(COPTS) start.c

pdptest.obj: pdptest.c
  $(CC) $(COPTS) pdptest.c

stdio.obj: stdio.c
  $(CC) $(COPTS) stdio.c

string.obj: string.c
  $(CC) $(COPTS) string.c

stdlib.obj: stdlib.c
  $(CC) $(COPTS) stdlib.c

time.obj: time.c
  $(CC) $(COPTS) time.c

errno.obj: errno.c
  $(CC) $(COPTS) errno.c

assert.obj: assert.c
  $(CC) $(COPTS) assert.c

signal.obj: signal.c
  $(CC) $(COPTS) signal.c

locale.obj: locale.c
  $(CC) $(COPTS) locale.c

ctype.obj: ctype.c
  $(CC) $(COPTS) ctype.c

setjmp.obj: setjmp.c
  $(CC) $(COPTS) setjmp.c

math.obj: math.c
  $(CC) $(COPTS) math.c

fpfuncsb.obj: fpfuncsb.c
  $(CC) $(COPTS) fpfuncsb.c


./ ADD NAME=BL3      0100-04042-04042-1043-00058-00058-00000-PDPCLIB
CC=bcc
COPTS=-w -c -I. -I\bcos2\include -u- -O2

pdptest.exe: startup.obj pdptest.obj stdio.obj string.obj stdlib.obj \
       start.obj time.obj errno.obj assert.obj signal.obj locale.obj \
       ctype.obj setjmp.obj math.obj fpfuncsb.obj
  link386 /nologo /pm:vio startup+pdptest+stdio+string+stdlib+start\
       +time+errno+assert+signal+locale+ctype+setjmp+math+fpfuncsb,\
       pdptest.exe,nul.map,os2386.lib,nul.def
  if exist borland.lib del borland.lib
  tlib borland +startup.obj +stdio.obj +string.obj +stdlib.obj \
       +start.obj +time.obj +errno.obj +assert.obj +signal.obj +locale.obj \
       +ctype.obj +setjmp.obj +math.obj +fpfuncsb.obj

startup.obj: startup.asm
  tasm -oi -mx -w2 -DLINK386_FIX startup.asm

start.obj: start.c
  $(CC) $(COPTS) start.c

pdptest.obj: pdptest.c
  $(CC) $(COPTS) pdptest.c

stdio.obj: stdio.c
  $(CC) $(COPTS) stdio.c

string.obj: string.c
  $(CC) $(COPTS) string.c

stdlib.obj: stdlib.c
  $(CC) $(COPTS) stdlib.c

time.obj: time.c
  $(CC) $(COPTS) time.c

errno.obj: errno.c
  $(CC) $(COPTS) errno.c

assert.obj: assert.c
  $(CC) $(COPTS) assert.c

signal.obj: signal.c
  $(CC) $(COPTS) signal.c

locale.obj: locale.c
  $(CC) $(COPTS) locale.c

ctype.obj: ctype.c
  $(CC) $(COPTS) ctype.c

setjmp.obj: setjmp.c
  $(CC) $(COPTS) setjmp.c

math.obj: math.c
  $(CC) $(COPTS) math.c

fpfuncsb.obj: fpfuncsb.c
  $(CC) $(COPTS) fpfuncsb.c
./ ADD NAME=DOS      0100-04042-04042-1043-00018-00018-00000-PDPCLIB
CC=tcc
COPTS=-O -w -c -I. -ml

pdptest.exe: dosstart.obj pdptest.obj stdio.obj string.obj stdlib.obj \
       start.obj time.obj errno.obj assert.obj signal.obj locale.obj \
       ctype.obj setjmp.obj math.obj dossupc.obj dossupa.obj
  if exist borland.lib del borland.lib
  tlib borland +dosstart.obj +stdio.obj +string.obj +stdlib.obj
  tlib borland +start.obj +time.obj +errno.obj +assert.obj +signal.obj
  tlib borland +locale.obj +ctype.obj +setjmp.obj +math.obj
  tlib borland +dossupc.obj +dossupa.obj
  tlink dosstart+pdptest,pdptest.exe,nul.map,borland.lib,

.c.obj:
  $(CC) $(COPTS) $<

.asm.obj:
  tasm -mx -w2 $<
./ ADD NAME=EMX      0100-04042-04042-1043-00059-00059-00000-PDPCLIB
CC=gcc
COPTS=-c -Zomf -I. -O -DUSE_ASSEMBLER -D__OS2__

pdptest.exe: startup.obj pdptest.obj stdio.obj string.obj stdlib.obj \
       start.obj time.obj errno.obj assert.obj signal.obj locale.obj \
       ctype.obj setjmp.obj math.obj stringa.obj
  link386 /nologo /pm:vio startup+pdptest+stdio+string+stdlib+start\
       +time+errno+assert+signal+locale+ctype+setjmp+math+stringa,\
       pdptest.exe,nul.map,os2386.lib,nul.def
  rm -f emx.lib
  lib /nologo emx startup.obj stdio.obj string.obj stdlib.obj \
       start.obj time.obj errno.obj assert.obj signal.obj locale.obj \
       ctype.obj setjmp.obj math.obj stringa.obj,,

startup.obj: startup.asm
  wasm -zq startup.asm

stringa.obj: stringa.asm
  wasm -zq stringa.asm

start.obj: start.c
  $(CC) $(COPTS) start.c

pdptest.obj: pdptest.c
  $(CC) $(COPTS) pdptest.c

stdio.obj: stdio.c
  $(CC) $(COPTS) stdio.c

string.obj: string.c
  $(CC) $(COPTS) string.c

stdlib.obj: stdlib.c
  $(CC) $(COPTS) stdlib.c

time.obj: time.c
  $(CC) $(COPTS) time.c

errno.obj: errno.c
  $(CC) $(COPTS) errno.c

assert.obj: assert.c
  $(CC) $(COPTS) assert.c

signal.obj: signal.c
  $(CC) $(COPTS) signal.c

locale.obj: locale.c
  $(CC) $(COPTS) locale.c

ctype.obj: ctype.c
  $(CC) $(COPTS) ctype.c

setjmp.obj: setjmp.c
  $(CC) $(COPTS) setjmp.c

math.obj: math.c
  $(CC) $(COPTS) math.c

./ ADD NAME=IBM      0100-04042-04042-1043-00058-00058-00000-PDPCLIB
CC=icc
COPTS=-c -Xc -I. -Gn -Tl- -Q -Gi -O -Oi500

pdptest.exe: startup.obj pdptest.obj stdio.obj string.obj stdlib.obj \
       start.obj time.obj errno.obj assert.obj signal.obj locale.obj \
       ctype.obj setjmp.obj math.obj fpfuncsc.obj
  link386 /nologo /pm:vio startup+pdptest+stdio+string+stdlib+start\
       +time+errno+assert+signal+locale+ctype+setjmp+math+fpfuncsc,\
       pdptest.exe,nul.map,os2386.lib,nul.def
  if exist cset.lib del cset.lib
  lib /nologo cset startup.obj stdio.obj string.obj stdlib.obj \
       start.obj time.obj errno.obj assert.obj signal.obj locale.obj \
       ctype.obj setjmp.obj math.obj fpfuncsc.obj,,

startup.obj: startup.asm
  wasm -zq startup.asm

start.obj: start.c
  $(CC) $(COPTS) start.c

pdptest.obj: pdptest.c
  $(CC) $(COPTS) pdptest.c

stdio.obj: stdio.c
  $(CC) $(COPTS) stdio.c

string.obj: string.c
  $(CC) $(COPTS) string.c

stdlib.obj: stdlib.c
  $(CC) $(COPTS) stdlib.c

time.obj: time.c
  $(CC) $(COPTS) time.c

errno.obj: errno.c
  $(CC) $(COPTS) errno.c

assert.obj: assert.c
  $(CC) $(COPTS) assert.c

signal.obj: signal.c
  $(CC) $(COPTS) signal.c

locale.obj: locale.c
  $(CC) $(COPTS) locale.c

ctype.obj: ctype.c
  $(CC) $(COPTS) ctype.c

setjmp.obj: setjmp.c
  $(CC) $(COPTS) setjmp.c

math.obj: math.c
  $(CC) $(COPTS) math.c

fpfuncsc.obj: fpfuncsc.c
  $(CC) $(COPTS) fpfuncsc.c
./ ADD NAME=PDS      0100-04042-04042-1043-00027-00027-00000-PDPCLIB
CC=gcc
COPTS=-c -s -O -I. -I..\src -D__PDOS__

pdptest.exe: pdosst32.o pdptest.o stdio.o string.o stdlib.o \
       start.o time.o errno.o assert.o signal.o locale.o \
       ctype.o setjmp.o math.o pos.o support.o pdossupc.o
  if exist pdos.a del pdos.a
  ar r pdos.a pdosst32.o stdio.o string.o stdlib.o
  ar r pdos.a start.o time.o errno.o assert.o signal.o
  ar r pdos.a locale.o ctype.o setjmp.o math.o
  ar r pdos.a pos.o support.o pdossupc.o
  ld -o pdptest pdosst32.o pdptest.o pdos.a
  if exist pdptest.exe del pdptest.exe
  ren pdptest pdptest.exe

pos.o: ..\src\pos.c
  $(CC) $(COPTS) ..\src\pos.c

support.o: ..\src\support.s
  $(CC) $(COPTS) ..\src\support.s

.c.o:
  $(CC) $(COPTS) $<

.s.o:
  $(CC) $(COPTS) $<

./ ADD NAME=PWC      0100-04042-04042-1043-00018-00018-00000-PDPCLIB
# Makefile for Power C (doesn't work though)

CC=pc
COPTS=-w -I. -ml -D__MSDOS__

pdptest.exe: dosstart.mix stdio.mix string.mix stdlib.mix \
       start.mix time.mix errno.mix assert.mix signal.mix locale.mix \
       ctype.mix setjmp.mix math.mix fpfuncsb.mix
  $(CC) $(COPTS) pdptest.c
  pcl pdptest,powerc

dosstart.mix: dosstart.asm
  tasm -mx -w2 dosstart.asm
#  mix dosstart.obj dosstart.mix

.c.mix:
  $(CC) $(COPTS) $<
  merge powerc $*
./ ADD NAME=WAT      0100-04042-04042-1043-00020-00020-00000-PDPCLIB
CC=wcl386
COPTS=-wx -c -I. -y -fpi87 -s -zq -3s -zm -zl -oneatx

pdptest.exe: startup.obj pdptest.obj stdio.obj string.obj stdlib.obj \
       start.obj time.obj errno.obj assert.obj signal.obj locale.obj \
       ctype.obj setjmp.obj math.obj fpfuncsw.obj
#Debug All
  if exist watcom.lib del watcom.lib
  wlib -q watcom startup.obj stdio.obj string.obj stdlib.obj \
       start.obj time.obj errno.obj assert.obj signal.obj locale.obj \
       ctype.obj setjmp.obj math.obj fpfuncsw.obj
  wlink File pdptest.obj \
        Name pdptest.exe \
        Library watcom.lib Library os2386.lib

startup.obj: startup.asm
  wasm -zq startup.asm

.c.obj:
  $(CC) $(COPTS) $<
./ ADD NAME=WCD      0100-04042-04042-1043-00073-00073-00000-PDPCLIB
CC=wcl
COPTS=-w -c -I. -ml -zl -D__MSDOS__ -fpi87 -s -d2 -zdp -zu

pdptest.exe: dosstart.obj pdptest.obj stdio.obj string.obj stdlib.obj \
       start.obj time.obj errno.obj assert.obj signal.obj locale.obj \
       ctype.obj setjmp.obj math.obj fpfuncsb.obj
#  wlink dosstart+pdptest+stdio+string+stdlib+start+time+errno\
#        +assert+signal+locale+ctype+setjmp+math+fpfuncsb,\
#        pdptest.exe,nul.map,,
  if exist watcom.lib del watcom.lib
  wlib -b watcom +dosstart.obj
  wlib -b watcom +stdio.obj
  wlib -b watcom +string.obj
  wlib -b watcom +stdlib.obj
  wlib -b watcom +start.obj
  wlib -b watcom +time.obj
  wlib -b watcom +errno.obj
  wlib -b watcom +assert.obj
  wlib -b watcom +signal.obj
  wlib -b watcom +locale.obj
  wlib -b watcom +ctype.obj
  wlib -b watcom +setjmp.obj
  wlib -b watcom +math.obj
  wlib -b watcom +fpfuncsb.obj
  wlink File pdptest.obj Name pdptest.exe Library watcom.lib

dosstart.obj: dosstart.asm
  wasm -DWATCOM dosstart.asm

start.obj: start.c
  $(CC) $(COPTS) start.c

pdptest.obj: pdptest.c
  $(CC) $(COPTS) pdptest.c

stdio.obj: stdio.c
  $(CC) $(COPTS) stdio.c

string.obj: string.c
  $(CC) $(COPTS) string.c

stdlib.obj: stdlib.c
  $(CC) $(COPTS) stdlib.c

time.obj: time.c
  $(CC) $(COPTS) time.c

errno.obj: errno.c
  $(CC) $(COPTS) errno.c

assert.obj: assert.c
  $(CC) $(COPTS) assert.c

signal.obj: signal.c
  $(CC) $(COPTS) signal.c

locale.obj: locale.c
  $(CC) $(COPTS) locale.c

ctype.obj: ctype.c
  $(CC) $(COPTS) ctype.c

setjmp.obj: setjmp.c
  $(CC) $(COPTS) setjmp.c

math.obj: math.c
  $(CC) $(COPTS) math.c

fpfuncsb.obj: fpfuncsb.c
  $(CC) $(COPTS) fpfuncsb.c



./ ADD NAME=WL3      0100-04042-04042-1043-00060-00060-00000-PDPCLIB
CC=wcl386
COPTS=-wx -c -I. -y -fpi87 -s -zq -3s -zm -d2

pdptest.exe: startup.obj pdptest.obj stdio.obj string.obj stdlib.obj \
       start.obj time.obj errno.obj assert.obj signal.obj locale.obj \
       ctype.obj setjmp.obj math.obj fpfuncsw.obj
  link386 /nologo /pm:vio startup+pdptest+stdio+string+stdlib+start\
       +time+errno+assert+signal+locale+ctype+setjmp+math+fpfuncsw,\
       pdptest.exe,nul.map,os2386.lib,nul.def
  if exist watcom.lib del watcom.lib
  wlib -q watcom startup.obj stdio.obj string.obj stdlib.obj \
       start.obj time.obj errno.obj assert.obj signal.obj locale.obj \
       ctype.obj setjmp.obj math.obj fpfuncsw.obj

startup.obj: startup.asm
  wasm -zq startup.asm

start.obj: start.c
  $(CC) $(COPTS) start.c

pdptest.obj: pdptest.c
  $(CC) $(COPTS) pdptest.c

stdio.obj: stdio.c
  $(CC) $(COPTS) stdio.c

string.obj: string.c
  $(CC) $(COPTS) string.c

stdlib.obj: stdlib.c
  $(CC) $(COPTS) stdlib.c

time.obj: time.c
  $(CC) $(COPTS) time.c

errno.obj: errno.c
  $(CC) $(COPTS) errno.c

assert.obj: assert.c
  $(CC) $(COPTS) assert.c

signal.obj: signal.c
  $(CC) $(COPTS) signal.c

locale.obj: locale.c
  $(CC) $(COPTS) locale.c

ctype.obj: ctype.c
  $(CC) $(COPTS) ctype.c

setjmp.obj: setjmp.c
  $(CC) $(COPTS) setjmp.c

math.obj: math.c
  $(CC) $(COPTS) math.c

fpfuncsw.obj: fpfuncsw.c
  $(CC) $(COPTS) fpfuncsw.c


